title : Blog Title
tagline: Blog Tagline
author :
  name : Yura Rodchyn
  email : rodchyn@gmail.com
  github : rodchyn
  twitter : rodchyn
  feedburner : rodchyn

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
